# import requests
#
# def get_postcode(street, city):
#     url = f"https://nominatim.openstreetmap.org/search?street={street}&city={city}&format=json"
#     response = requests.get(url).json()
#     if response:
#         return response[0]['address'].get('postcode')
#     else:
#         return None


# with open('../data_lists/strassenBerlin.txt', 'r') as f:
#   data = f.readlines()
#
# strassen = [line.strip() for line in data]
# bezirke = []
# # print(strassen[3203:3252])
#
# with open('../data_lists/strassenPlzBerlin.txt', 'r') as f:
#   data = f.readlines()
# strassen_plz = []
#
#
# for line in data:
#   arr = line.strip().split(',')
#   strassen_plz.append(f"{arr[0]},{arr[1]}")
#
# print(strassen_plz[200:250])

addresses = [
  ['Abendfrieden', 'Johannisthal', '12487'],
  ['Abramowitschallee', 'Johannisthal', '12489'],
  ['Akademieplatz', 'Johannisthal', '12489'],
  ['Akeleiweg', 'Johannisthal', '12489'],
  ['Albineaplatz', 'Johannisthal', '12487'],
  ['Allee Marie Curie', 'Wittenau', '13405'],
  ['Allee Pierre de Coubertin', 'Wittenau', '13403'],
  ['Allmersweg', 'Johannisthal', '12489'],
  ['Alter Segelfliegerdamm', 'Johannisthal', '12487'],
  ['Am Alten Fenn', 'Johannisthal', '12487'],
  ['Am Bürgerpark', 'Reinickendorf', '13467'],
  ['Am Buschfeld', 'Buckow', '12351'],
  ['Am Dählingsberg', 'Französisch Buchholz', '13127'],
  ['Am Damm', 'Friedrichshagen', '12587'],
  ['Am Festplatz', 'Wedding', '13353'],
  ['Am Festungsgraben', 'Mitte', '10117'],
  ['Am Fliederbusch', 'Westend', '14055'],
  ['Am Grünen Anger', 'Johannisthal', '12487'],
  ['Am Haselbusch', 'Johannisthal', '12487'],
  ['Am Kraatz-Tränke-Graben', 'Friedrichsfelde', '10315'],
  ['Am Krähenberg', 'Konradshöhe', '13505'],
  ['Am Wuhlebogen', 'Biesdorf', '12683'],
  ['Amselstraße', 'Johannisthal', '12487'],
  ['An den Eiswerken', 'Rummelsburg', '10319'],
  ['An den Hubertshäusern', 'Nikolassee', '14129'],
  ['An der Brücke', 'Grünau', '12527'],
  ['An der Schutzbepflanzung', 'Hellersdorf', '12627'],
  ['An der Streuobstwiese', 'Französisch Buchholz', '13127'],
  ['Andreasplatz', 'Friedrichshain', '10243'],
  ['Anna-Mungunda-Allee', 'Wedding', '13355'],
  ['Anton-Wilhelm-Amo-Straße', 'Mitte', '10178'],
  ['Apfelallee', 'Französisch Buchholz', '13127'],
  ['Arberlandplatz', 'Karlshorst', '10318'],
  ['Arnbrucker Straße', 'Karlshorst', '10318'],
  ['Auf dem Oktogon', 'Adlershof', '12489'],
  ['August-Bebel-Straße', 'Rahnsdorf', '12589'],
  ['BAB-Tunnel Flughafen Tegel', 'Tegel', '13505'],
  ['Bahnhofplatz', 'Hermsdorf', '13467'],
  ['Beeskowdamm', 'Lichterfelde', '12207'],
  ['Bernhard-Wieck-Promenade', 'Grunewald', '14193'],
  ['Beyschlagtunnel', 'Heiligensee', '13503'],
  ['Birkbuschgartenpark', 'Steglitz', '12167'],
  ['Birkenplatz', 'Grunewald', '14193'],
  ['Bischofsmaiser Straße', 'Karlshorst', '10318'],
  ['Blaubeerweg', 'Französisch Buchholz', '13127'],
  ['Bleichröderpark', 'Pankow', '13187'],
  ['Blumeneschenweg', 'Kaulsdorf', '12621'],
  ['Bohnsdorfer Chaussee', 'Altglienicke', '12526'],
  ['Bollesteg', 'Tegel', '13505'],
  ['Briesener Weg', 'Kaulsdorf', '12621'],
  ['Britzer Zweigkanal', 'Neukölln', '12357'],
  ['Brombeerweg', 'Französisch Buchholz', '13127'],
  ['Brücke am Jakob-Kaiser-Platz', 'Charlottenburg', '13627'],
  ['Brücke Teilestraße', 'Tempelhof', '12099'],
  ['Am Kraatz-Tränke-Graben', 'Friedrichsfelde', '10319'],
  ['Am Krähenberg', 'Konradshöhe', '13505'],
  ['Am Wuhlebogen', 'Biesdorf', '12683'],
  ['Amselstraße', 'Johannisthal', '12487'],
  ['An den Eiswerken', 'Rummelsburg', '10319'],
  ['An den Hubertshäusern', 'Nikolassee', '14129'],
  ['An der Brücke', 'Grünau', '12527'],
  ['An der Schutzbepflanzung', 'Hellersdorf', '12621'],
  ['An der Streuobstwiese', 'Französisch Buchholz', '13127'],
  ['Andreasplatz', 'Friedrichshain', '10243'],
  ['Anna-Mungunda-Allee', 'Wedding', '13353'],
  ['Anton-Wilhelm-Amo-Straße', 'Mitte', '10178'],
  ['Apfelallee', 'Französisch Buchholz', '13127'],
  ['Arberlandplatz', 'Karlshorst', '10318'],
  ['Arnbrucker Straße', 'Karlshorst', '10318'],
  ['Auf dem Oktogon', 'Adlershof', '12489'],
  ['August-Bebel-Straße', 'Rahnsdorf', '12589'],
  ['BAB-Tunnel Flughafen Tegel', 'Tegel', '13507'],
  ['Bahnhofplatz', 'Hermsdorf', '13467'],
  ['Beeskowdamm', 'Lichterfelde', '12279'],
  ['Bernhard-Wieck-Promenade', 'Grunewald', '14193'],
  ['Beyschlagtunnel', 'Heiligensee', '13503'],
  ['Birkbuschgartenpark', 'Steglitz', '12167'],
  ['Birkenplatz', 'Grunewald', '14193'],
  ['Bischofsmaiser Straße', 'Karlshorst', '10318'],
  ['Blaubeerweg', 'Französisch Buchholz', '13127'],
  ['Bleichröderpark', 'Pankow', '13189'],
  ['Blumeneschenweg', 'Kaulsdorf', '12621'],
  ['Bohnsdorfer Chaussee', 'Altglienicke', '12526'],
  ['Bollesteg', 'Tegel', '13505'],
  ['Briesener Weg', 'Kaulsdorf', '12621'],
  ['Britzer Zweigkanal', 'Neukölln', '12347'],
  ['Brombeerweg', 'Französisch Buchholz', '13127'],
  ['Brücke am Jakob-Kaiser-Platz', 'Charlottenburg', '10555'],
  ['Brücke Teilestraße', 'Tempelhof', '12103'],
  ['Brücke Waidmannsluster Damm', 'Tegel', '13507'],
  ['Brunnengalerie', 'Köpenick', '12555'],
  ['Brunnensteg', 'Tegel', '13507'],
  ['Buddestraßenbrücke', 'Tegel', '13507'],
  ['Buschiner Platz', 'Biesdorf', '12683'],
  ['Carl-Julius-Vogel-Straße', 'Adlershof', '12489'],
  ['Cecilienplatz', 'Hermsdorf', '13467'],
  ['Charles-Boutard-Straße', 'Johannisthal', '12487'],
  ['Charlottenburger Chaussee', 'Westend', '14052'],
  ['Charlottenburger Schleuse', 'Charlottenburg', '10585'],
  ['Cité Joffre', 'Reinickendorf', '13403'],
  ['Condéstraße', 'Französisch Buchholz', '13127'],
  ['Daimlerstraße', 'Mariendorf', '12105'],
  ['Dämeritzsee', 'Rahnsdorf', '12589'],
  ['Dammweg', 'Wilhelmstadt', '13593'],
  ['Dammwegbrücke', 'Baumschulenweg', '12437'],
  ['Däumlingweg', 'Stadtrandsiedlung Malchow', '13051'],
  ['Daumstraßenbrücke', 'Haselhorst', '13599'],
  ['Der Breite Weg', 'Tegel', '13507'],
  ['Der Insulaner', 'Schöneberg', '12167'],
  ['Dietrichplatz', 'Alt-Hohenschönhausen', '13053'],
  ['Dr.-Jacoby-Weg', 'Friedrichshagen', '12587'],
  ['Dreibock', 'Rahnsdorf', '12589'],
  ['Egidysteg', 'Tegel', '13507'],
  ['Eichbornbrücke', 'Wittenau', '13403'],
  ['Eigene Scholle', 'Johannisthal', '12487'],
  ['Eigenheim I + II', 'Johannisthal', '12487'],
  ['Einemweg', 'Britz', '12349'],
  ['Ekhofstraßenbrücke', 'Köpenick', '12555'],
  ['Elfensteig', 'Gatow', '14089'],
  ['Elkartweg jetzt Erna-Koschwitz-Weg', 'Hakenfelde', '13587'],
  ['Elsa-Neumann-Straße', 'Haselhorst', '13599'],
  ['Elsterstraße', 'Johannisthal', '12487'],
  ['Entenwall', 'Rahnsdorf', '12589'],
  ['Eosanderplatz', 'Charlottenburg', '10587'],
  ['Erlenbuschpark', 'Dahlem', '14195'],
  ['Ernst-Reuter-Siedlung', 'Gesundbrunnen', '13353'],
  ['Eßlinger Steig', 'Frohnau', '13465'],
  ['Carl-Schurz-Brücke', 'Spandau', '13597'],
  ['Ettaler Straße', 'Schöneberg', '10781'],
  ['Eugen-Roth-Weg', 'Biesdorf', '12683'],
  ['Eva-Strittmatter-Straße', 'Hellersdorf', '12619'],
  ['Falkenberger Brücke', 'Neu-Hohenschönhausen', '13053'],
  ['Felsenfest', 'Johannisthal', '12487'],
  ['Festplatzweg', 'Wilhelmstadt', '13593'],
  ['Finsterwalder Brücke', 'Märkisches Viertel', '13435'],
  ['Flatowalleebrücke', 'Westend', '14055'],
  ['Formosa', 'Johannisthal', '12489'],
  ['Forstmeisterweg', 'Rahnsdorf', '12589'],
  ['Forum an der Museumsinsel', 'Mitte', '10178'],
  ['Föttingerzeile', 'Mariendorf', '12107'],
  ['Frau Elster-Weg', 'Weißensee', '13086'],
  ['Frauenplatz', 'Westend', '14052'],
  ['Freizeitpark Hahneberg', 'Staaken', '13591'],
  ['Fresepark', 'Marienfelde', '12107'],
  ['Fürst-Bismarck-Steg', 'Waidmannslust', '13469'],
  ['Fußgängerbrücke im Zuge des Volksparkes', 'Wilmersdorf', '10709'],
  ['Fußgängertunnel Ernst-Reuter-Platz', 'Charlottenburg', '10587'],
  ['Fußgängertunnel Kurt-Schumacher-Damm', 'Charlottenburg', '13627'],
  ['Fußgängertunnel S-Bahn Friedenau', 'Schöneberg', '12161'],
  ['Fußgängertunnel Sybelstraße/Waitzstraße', 'Charlottenburg', '10629'],
  ['Fußgängertunnel zum Adenauerplatz', 'Charlottenburg', '10709'],
  ['Fußgängertunnel Ernst-Reuter-Platz', 'Charlottenburg', '10587'],
  ['Gänsewerder', 'Tegel', '13505'],
  ['Gartenufer', 'Tiergarten', '10555'],
  ['Geißenweide', 'Biesdorf', '12683'],
  ['Gerichtstraßenbrücke', 'Wedding', '13347'],
  ['Gnomensteig', 'Gatow', '14089'],
  ['Gottlieb-Dunkel-Straßen-Brücke', 'Tempelhof', '12101'],
  ['Gottschalkbrücke', 'Gesundbrunnen', '13357'],
  ['Gradestraßenbrücke', 'Britz', '12347'],
  ['Griebnitzsee-Promenade', 'Wannsee', '14193'],
  ['Griebnitzseekanal', 'Wannsee', '14109'],
  ['Grimmener Straße', 'Biesdorf', '12683'],
  ['Großer Rohrwall', 'Grünau', '12527'],
  ['Großer Stern', 'Grunewald', '10557'],
  ['Grottewitzwanderweg', 'Müggelheim', '12559'],
  ['Grüne Brücke', 'Heiligensee', '13503'],
  ['Grützmachergraben-Brücke', 'Haselhorst', '13599'],
  ['Guntersblumer Weg', 'Nikolassee', '14129'],
  ['Guntherweg', 'Johannisthal', '12347'],
  ['Gustav-Tempel-Straße', 'Rummelsburg', '10317'],
  ['Hackbuschsteg', 'Staaken', '13591'],
  ['Hafen Altglienicke', 'Altglienicke', '12524'],
  ['Hafen Britz West', 'Britz', '12359'],
  ['Hafen Lichterfelde', 'Lichterfelde', '12203'],
  ['Hafen Rudow-Ost', 'Neukölln', '12357'],
  ['Hafen Rudow-West', 'Neukölln', '12353'],
  ['Hafen Steglitz', 'Lichterfelde', '12203'],
  ['Hafenbrücke Neheimer Straße', 'Tegel', '13507'],
  ['Hans-Rosenthal-Platz', 'Schöneberg', '10713'],
  ['Hans-Sachs-Straße', 'Baumschulenweg', '12437'],
  ['Hauptweg', 'Blankenfelde', '13159'],
  ['Haveleck', 'Wannsee', '14109'],
  ['Hebammensteigbrücke', 'Französisch Buchholz', '13127'],
  ['Hegemeisterbrücke', 'Rahnsdorf', '12589'],
  ['Heidegarten', 'Tempelhof', '12103'],
  ['Heidetor', 'Spandau', '13597'],
  ['Heimatscholle', 'Johannisthal', '12347'],
  ['Heiner-Carow-Straße', 'Rummelsburg', '10317'],
  ['Heinrich-Hertz-Straße', 'Haselhorst', '13599'],
  ['Heinrichplatz jetzt Rio-Reiser-Platz', 'Kreuzberg', '10967'],
  ['Heliosstraße', 'Biesdorf', '12683'],
  ['Helmut-Brenner-Straße', 'Adlershof', '12489'],
  ['Henry-Farman-Straße', 'Johannisthal', '12487'],
  ['Hertzallee', 'Tiergarten', '10587'],
  ['Hoffnung', 'Johannisthal', '12347'],
  ['Holunderweg', 'Französisch Buchholz', '13127'],
  ['Holzhauser Brücke', 'Tegel', '13509'],
  ['Hortensienweg', 'Französisch Buchholz', '13127'],
  ['Hubert-Latham-Straße', 'Johannisthal', '12487'],
  ['Hugo-Heimann-Brücke', 'Wedding', '13353'],
  ['Humboldthafen', 'Moabit', '10555'],
  ['Humboldthöhe', 'Gesundbrunnen', '13357'],
  ['Humboldtmühlenbrücke', 'Tegel', '13597'],
  ['Hummelweg', 'Blankenburg', '13129'],
  ['Igo-Etrich-Straße', 'Johannisthal', '12487'],
  ['Ilse-Krause-Straße', 'Buch', '13125'],
  ['Ilsestraße', 'Rummelsburg', '10318'],
  ['Immergrün', 'Johannisthal', '12487'],
  ['Ingrid-Reschke-Straße', 'Rummelsburg', '10319'],
  ['Jakobikirchstraße', 'Kreuzberg', '10969'],
  ['Jeanne-Baret-Straße', 'Köpenick', '12559'],
  ['Johannisbeerweg', 'Französisch Buchholz', '13127'],
  ['Josef-Orlopp-Straße', 'Fennpfuhl', '10365'],
  ['Jungfernsee', 'Wannsee', '14109'],
  ['Kaiserkronenweg', 'Biesdorf', '12683'],
  ['Kamisardenplatz', 'Französisch Buchholz', '13127'],
  ['Kapweg', 'Wedding', '13357'],
  ['Karolinenbrücke', 'Tegel', '13507'],
  ['Kastanienweg', 'Altglienicke', '12524'],
  ['Kaumanns Gasse', 'Köpenick', '12555'],
  ['Kiefholzbrücke', 'Alt-Treptow', '12435'],
  ['Kiesbergplatz', 'Altglienicke', '12524'],
  ['Kirchplatz', 'Wittenau', '13437'],
  ['Kol. Scharzhofberger Platz', 'Lankwitz', '12249'],
  ['Köllnische Brücke', 'Niederschöneweide', '12439'],
  ['Königin-Luise-Straße', 'Lichterfelde', '14195'],
  ['Köthener Straße', 'Tiergarten', '10777'],
  ['Krielower Platz', 'Gatow', '14089'],
  ['Kuckucksstraße', 'Johannisthal', '12487'],
  ['Kurhausstraßenbrücke', 'Waidmannslust', '13469'],
  ['Küstriner Platz', 'Lichtenrade', '12307'],
  ['Landsberger Tor', 'Marzahn', '12685'],
  ['Langdorfer Straße', 'Karlshorst', '10318'],
  ['Laubacher Straße', 'Friedenau', '12161'],
  ['Laurinsteg', 'Johannisthal', '12487'],
  ['Lennédreieck', 'Tiergarten', '10785'],
  ['Lerchenstraße', 'Johannisthal', '12487'],
  ['Lichtenrader Damm', 'Buckow', '12305'],
  ['Lietzenseeufer', 'Charlottenburg', '14057'],
  ['Lindower Straße', 'Gesundbrunnen', '13347'],
  ['Lotte-Loebinger-Straße', 'Adlershof', '12489'],
  ['Luisenbrücke', 'Tiergarten', '10585'],
  ['Lusenpfad', 'Karlshorst', '10318'],
  ['Maerckerweg jetzt Maria-Rimkus-Weg', 'Lankwitz', '12247'],
  ['Magarethe-Kubicka-Brücke', 'Neukölln', '12053'],
  ['Maiglöckchenweg', 'Heinersdorf', '13089'],
  ['Maji-Maji-Allee', 'Wedding', '13351'],
  ['Mariendorfer-Hafen-Steg', 'Mariendorf', '12109'],
  ['Marius-Carpentier-Straße', 'Hakenfelde', '13587'],
  ['Markgrafenstraße', 'Kaulsdorf', '12621'],
  ['Marzahner Straße', 'Falkenberg', '12689'],
  ['Maselakeweg', 'Hakenfelde', '13587'],
  ['Mathilde-Rathenau-Brücke', 'Alt-Treptow', '12435'],
  ['Maulbeerweg', 'Französisch Buchholz', '13127'],
  ['Meisenweg', 'Wilhelmstadt', '13599'],
  ['Messedammbrücke', 'Westend', '14057'],
  ['Meta-London-Straße', 'Hakenfelde', '13587'],
  ['Minna-Cauer-Straße', 'Tiergarten', '10117'],
  ['Minna-Flake-Platz', 'Prenzlauer Berg', '10437'],
  ['Mittelheide', 'Hakenfelde', '13589'],
  ['Möwenstraße', 'Wannsee', '14109'],
  ['Mühlenstraße', 'Friedrichshagen', '12555'],
  ['Müllerstraße', 'Gesundbrunnen', '13349'],
  ['Muspelsteig', 'Heinersdorf', '13089'],
  ['Nachtigalplatz jetzt Manga-Bell-Platz', 'Wedding', '13357'],
  ['Neben dem Dorfteich', 'Wartenberg', '13059'],
  ['Neuer Weg', 'Wilhelmstadt', '13593'],
  ['Nieder-Neuendorfer See', 'Heiligensee', '13503'],
  ['Nikolai-E.-Bersarin-Brücke', 'Hellersdorf', '12619'],
  ['Nordendstraße', 'Rosenthal', '13156'],
  ['Normannenplatz', 'Altglienicke', '12524'],
  ['Nymphenbrücke', 'Nikolassee', '14129'],
  ['Okarinastraße', 'Niederschönhausen', '13156'],
  ['Oraniendammbrücke', 'Hermsdorf', '13467'],
  ['Osloer-Straßen-Brücke', 'Gesundbrunnen', '13359'],
  ['Osserweg', 'Karlshorst', '10318'],
  ['Paradeweg', 'Tiergarten', '10785'],
  ['Parforceweg', 'Grunewald', '14193'],
  ['Pasewalker Straße', 'Niederschönhausen', '13127'],
  ['Paul-und-Paula-Promenade', 'Rummelsburg', '10317'],
  ['Paule-Panke-Straße', 'Pankow', '13127'],
  ['Pergamonsteg', 'Mitte', '10178'],
  ['Petersililienweg', 'Friedrichshagen', '12587'],
  ['Pieperweg', 'Wilhelmstadt', '13595'],
  ['Pierre-de-Caters-Straße', 'Johannisthal', '12487'],
  ['Pionierinsel', 'Hakenfelde', '13587'],
  ['Platz 764', 'Schmöckwitz', '12527'],
  ['Platz 768', 'Schmöckwitz', '12527'],
  ['Platz 776', 'Schmöckwitz', '12527'],
  ['Platz 777', 'Schmöckwitz', '12527'],
  ['Platz am Königstor', 'Prenzlauer Berg', '10115'],
  ['Poetensteig', 'Plänterwald', '12435'],
  ['Poleigrund', 'Lichtenrade', '12309'],
  ['Prackenbacher Straße', 'Karlshorst', '10318'],
  ['Preiselbeerweg', 'Französisch Buchholz', '13127'],
  ['Prenzlauer Tor', 'Prenzlauer Berg', '10405'],
  ['Priesterweg', 'Johannisthal', '12487'],
  ['Prinzeßweg', 'Hakenfelde', '13599'],
  ['Pyramindenbrücke', 'Köpenick', '12559'],
  ['Quellpfad', 'Köpenick', '12559'],
  ['Rachelweg', 'Karlshorst', '10318'],
  ['Radolfzeller Weg', 'Zehlendorf', '14163'],
  ['Ravensteiner Promenade', 'Friedrichshagen', '12587'],
  ['Rehberge', 'Hakenfelde', '13509'],
  ['Reuterplatz', 'Reinickendorf', '13353'],
  ['Rheingoldstraße', 'Altglienicke', '12524'],
  ['Rita-Maiburg-Straße', 'Bohnsdorf', '12526'],
  ['Rixdorfer Höhe', 'Neukölln', '12099'],
  ['Roedernbrücke', 'Wittenau', '13437'],
  ['Rollbergweg', 'Rosenthal', '13158'],
  ['Rollettplatz', 'Johannisthal', '12487'],
  ['Rosa-Coutelle-Straße', 'Buch', '13125'],
  ['Rosa-Parks-Platz', 'Wedding', '13357'],
  ['Rose-Scheuer-Karpin-Straße', 'Buch', '13125'],
  ['Rosenthaler Grenzweg', 'Rosenthal', '13158'],
  ['Rosentreterpfad', 'Wittenau', '13437'],
  ['Rübezahlsteig', 'Gatow', '14089'],
  ['Rue René Laennec', 'Tegel', '13507'],
  ['Ruhegarten', 'Tiergarten', '10557'],
  ['Ruhmannsfeldener Straße', 'Karlshorst', '10318'],
  ['Rummelsburger Landstraße', 'Karlshorst', '10318'],
  ['Rummelsburger Seeblick', 'Rummelsburg', '10317'],
  ['Rumplerzeile', 'Johannisthal', '12353'],
  ['Ruthenberge', 'Reinickendorf', '13503'],
  ['Sachsendammbrücken', 'Schöneberg', '10829'],
  ['Saturnring', 'Altglienicke', '12524'],
  ['Saubuchtweg', 'Grunewald', '14193'],
  ['Schienenweg', 'Blankenfelde', '13159'],
  ['Schiffahrtsufer', 'Spandau', '13597'],
  ['Schilfanger', 'Falkenberg', '13057'],
  ['Schirwindter Brücke', 'Westend', '14052'],
  ['Schleuse Plötzensee', 'Charlottenburg', '14059'],
  ['Schleuseninsel', 'Tiergarten', '10559'],
  ['Schloßplatz', 'Hermsdorf', '13467'],
  ['Schloßstraßenbrücke', 'Tegel', '13507'],
  ['Schlütersteg', 'Heiligensee', '13503'],
  ['Schmargendorfer Brücke', 'Schmargendorf', '14199'],
  ['Schmöckwitzwerdersteg', 'Schmöckwitz', '12527'],
  ['Schneewittchensteig', 'Gatow', '14089'],
  ['Schneewittchenweg', 'Wannsee', '14109'],
  ['Schönauer Platz', 'Hakenfelde', '13587'],
  ['Schönhauser Tor', 'Prenzlauer Berg', '10119'],
  ['Schreckhornweg', 'Stadtrandsiedlung Malchow', '13051'],
  ['Schützenstraße', 'Reinickendorf', '13465'],
  ['Schwanenblumenweg', 'Falkenberg', '13057'],
  ['Schwarzbacher Brücke', 'Halensee', '14193'],
  ['Schwarzer Weg', 'Müggelheim', '12559'],
  ['Seestraßenbrücke (nördlich)', 'Moabit', '10555'],
  ['Seestraßenbrücke (südlich)', 'Moabit', '10557'],
  ['Seidelstraßenbrücke', 'Reinickendorf', '13409'],
  ['Sonnenalleebrücke', 'Neukölln', '12055'],
  ['Spreekanalpromenade', 'Mitte', '10179'],
  ['Sprosserweg', 'Gropiusstadt', '12353'],
  ['Stachelbeerweg', 'Französisch Buchholz', '13127'],
  ['Steinstraße', 'Wannsee', '14109'],
  ['Steinstücken', '', '14109'],
  ['Stellerweg', 'Alt-Hohenschönhausen', '13055'],
  ['Sternfelder Straße', 'Siemensstadt', '13627'],
  ['Sterntalerweg', 'Weißensee', '13086'],
  ['Ilse-Krause-Straße', 'Buch', '13125'],
  ['Rosa-Coutelle-Straße', 'Buch', '13125'],
  ['Straße zum Teufelsee', 'Köpenick', '12559'],
  ['Südtorweg', 'Westend', '14050'],
  ['Sundgauer Straße', 'Dahlem', '14169'],
  ['Süßdoldenweg', 'Rosenthal', '13158'],
  ['Taubestraße', 'Johannisthal', '12487'],
  ['Teichrohrplatz', 'Altglienicke', '12524'],
  ['Teilestraßenbrücke', 'Tempelhof', '12103'],
  ['Telegrafenwegbrücke', 'Haselhorst', '13599'],
  ['Teltower Brücke', 'Wilhelmstadt', '13597'],
  ['Teltower Schanze', 'Wilhelmstadt', '13595'],
  ['Tiefland', 'Johannisthal', '12487'],
  ['Tiergartenschleusen-Brücke', 'Tiergarten', '10557'],
  ['Tile-Brügge-Steg', 'Tegel', '13507'],
  ['Tollerstraße', 'Niederschönhausen', '13156'],
  ['Torstraße', 'Prenzlauer Berg', '10119'],
  ['Treidelweg', 'Charlottenburg', '13627'],
  ['Treidelweg', 'Johannisthal', '12487'],
  ['Treptower Brücke', 'Kreuzberg', '10963'],
  ['Triftbrücke', 'Wittenau', '13437'],
  ['Triftweg', 'Gatow', '14089'],
  ['Trümmerberg', 'Friedrichsfelde', '10315'],
  ['Tulpenweg', 'Stadtrandsiedlung Malchow', '13051'],
  ['Tunnel Kaiser-Friedrich-Straße', 'Charlottenburg', '10627'],
  ['Tunnel Siegessäule', 'Tiergarten', '10785'],
  ['Uferpromenade Fischerinsel', 'Mitte', '10179'],
  ['Ulrich-Plenzdorf-Straße', 'Rummelsburg', '10317'],
  ['Valentinswerder (Insel)', 'Tegel', '13505'],
  ['Verlängerte Semmelweisstraße', 'Altglienicke', '12524'],
  ['Violastraße', 'Wartenberg', '13059'],
  ['Wacholderweg', 'Französisch Buchholz', '13127'],
  ['Wagner-Régeny-Straße', 'Johannisthal', '12487'],
  ['Waldmeisterstraße', 'Schmargendorf', '14199'],
  ['Waldpark Steinberg', 'Waidmannslust', '13469'],
  ['Waldseepark', 'Hermsdorf', '13467'],
  ['Werdauer-Weg-Brücke', 'Schöneberg', '10829'],
  ['Werner-Klemke-Platz', 'Weißensee', '13086'],
  ['Westdamm', 'Westend', '14059'],
  ['Westhafenkanal', 'Charlottenburg-Nord', '13627'],
  ['Weverpromenade', 'Steglitz', '12161'],
  ['Wiener Brücke', 'Kreuzberg', '10999'],
  ['Wiesendammbrücke', 'Spandau', '13597'],
  ['Wiesenweg', 'Lichterfelde', '12209'],
  ['Winterhuder Steg', 'Staaken', '13591'],
  ['Wolfgang-Liebe-Straße', 'Adlershof', '12489'],
  ['Ziekow-Brücke', 'Tegel', '13507'],
  ['Zimmerstraße', 'Kreuzberg', '10969'],
  ['Zitadellenwegbrücke', 'Haselhorst', '13599'],
  ['Zugbrücke', 'Haselhorst', '13599'],
  ['Züllichauer Straße', 'Tempelhof', '12101'],
  ['Zum Betriebsbahnhof', 'Friedrichsfelde', '10315'],
  ['Zum Glühwürmchengrund', 'Hakenfelde', '13503'],
  ['Zur Plauener Straße', 'Alt-Hohenschönhausen', '13051'],
  ['Zur Schönagelstraße', 'Marzahn', '12681']
]
# for line in strassen:
#   if line in strassen_plz:
#     continue
#   address = line.split(',')
#   print(address)
#   addresses.append(address)


with open('../data_lists/strassenPlzBerlin.txt', 'a') as f:
  for address in addresses:
    f.write(f'{address[0]},{address[1]},{address[2]}\n')


# for address in addresses:
#     postcode = get_postcode(address[0], address[1])
#     print(f"{address}, {postcode}")
#


# for line in strassen:
#   if line[1] in bezirke or line[1] == '':
#     continue
#   bezirke.append(line[1])
# print(len(bezirke))
# bezirke.sort()
#
# print(bezirke)

# import requests
# url = "https://nominatim.openstreetmap.org/search.php"
# with open('../data_lists/strassenPlzBerlin.txt', 'a') as f:
#   for s in strassen[485:]:
#
#     try:
#       street = f"{s[0]},{s[1]}"
#       print(street)
#       parameters = {
#         "q": street,
#         "format": "jsonv2"
#       }
#       response = requests.get(url, params=parameters)
#       result = response.json()[0]['display_name']
#       plz = result.split(',')[-2]
#       f.write(f"{street},{plz.strip()}\n")
#     except IndexError:
#       print('--------------------------------------')
#       continue
